# Generated by Django 3.2.16 on 2024-10-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(max_length=50, verbose_name='^[0-9a-zA-Z]*$'),
        ),
    ]
